const express = require('express');
const multer = require('multer');
const path = require('path');
const mongoose = require('mongoose');
const Booking = require('../../models/Booking');
const ChatConversation = require('../../models/ChatConversation');
const ChatMessage = require('../../models/ChatMessage');

function createChatRouter({ verifyAuth, uploadsDir }) {
  const router = express.Router();
  const storage = multer.diskStorage({
    destination: (_req, _file, callback) => callback(null, uploadsDir),
    filename: (_req, file, callback) => {
      const extension = path.extname(file.originalname).toLowerCase() || '.pdf';
      callback(null, `${Date.now()}-${Math.round(Math.random() * 1e9)}${extension}`);
    },
  });
  const upload = multer({
    storage,
    limits: { fileSize: 25 * 1024 * 1024 },
    fileFilter: (_req, file, callback) => {
      const isPdf = file.mimetype === 'application/pdf' || file.originalname.toLowerCase().endsWith('.pdf');
      callback(isPdf ? null : new Error('Chat attachments must be PDF files.'), isPdf);
    },
  });

  router.get('/:conversationId', verifyAuth, async (req, res) => {
    try {
      const conversation = await findConversation(req.params.conversationId);
      if (!conversation || !isParticipant(conversation, req.user)) {
        return res.status(404).json({ error: 'Conversation not found.' });
      }
      const booking = await findBooking(conversation.bookingId);
      if (!booking ||
          booking.planType !== 'monthly' ||
          !['CONFIRMED', 'ACTIVE'].includes(booking.status) ||
          !booking.planEndsAt ||
          new Date(booking.planEndsAt) <= new Date()) {
        return res.status(403).json({ error: 'Chat is available only during an active monthly mentorship.' });
      }
      const after = req.query.after ? new Date(req.query.after) : null;
      if (mongoose.connection.readyState === 1) {
        const query = { conversationId: conversation._id };
        if (after && Number.isFinite(after.getTime())) query.createdAt = { $gt: after };
        const messages = await ChatMessage.find(query).sort({ createdAt: 1 }).limit(200);
        return res.json(messages);
      }
      const messages = (global.ymentorMemoryStore.messages || []).filter((message) =>
        String(message.conversationId) === String(conversation._id) &&
        (!after || new Date(message.createdAt) > after),
      );
      return res.json(messages);
    } catch (error) {
      console.error('Chat history error:', error);
      return res.status(500).json({ error: 'Unable to load conversation.' });
    }
  });

  router.post('/send', verifyAuth, upload.single('pdf'), async (req, res) => {
    try {
      const {
        conversationId,
        text = '',
        sessionType,
        messageType = 'USER',
        preset,
      } = req.body;
      if (!conversationId || (!String(text).trim() && !req.file)) {
        return res.status(400).json({ error: 'A message or PDF attachment is required.' });
      }
      const conversation = await findConversation(conversationId);
      if (!conversation || !isParticipant(conversation, req.user)) {
        return res.status(404).json({ error: 'Conversation not found.' });
      }
      const booking = await findBooking(conversation.bookingId);
      if (!booking || !['CONFIRMED', 'ACTIVE'].includes(booking.status)) {
        return res.status(403).json({ error: 'Chat is available only during a confirmed mentorship.' });
      }
      const bookingType = String(sessionType || booking.planType || 'hourly').toUpperCase();
      if (bookingType === 'HOURLY' || booking.planType === 'hourly') {
        const allowedPresets = new Set([
          'SESSION_BOOKED',
          'MEET_LINK_GENERATED',
          'FIFTEEN_MINUTES_REMAINING',
          'UPLOAD_WORKSPACE_CODE',
        ]);
        if (String(messageType).toUpperCase() === 'SYSTEM' && allowedPresets.has(String(preset))) {
          return res.status(403).json({
            error: 'Hourly system updates are generated by the session service.',
          });
        }
        return res.status(403).json({
          error: 'Direct chat is disabled for hourly micro-sessions. Upgrade to Monthly Mentorship for unlimited chat.',
        });
      }
      if (bookingType !== 'MONTHLY' ||
          booking.planType !== 'monthly' ||
          !booking.planEndsAt ||
          new Date(booking.planEndsAt) <= new Date()) {
        return res.status(403).json({ error: 'Chat is available only during an active monthly mentorship.' });
      }
      const messageData = {
        conversationId: conversation._id,
        senderId: req.user._id || req.user.id,
        text: String(text).trim(),
        attachmentUrl: req.file ? `/uploads/${path.basename(req.file.path)}` : '',
        createdAt: new Date(),
      };
      let message;
      if (mongoose.connection.readyState === 1) {
        message = await ChatMessage.create(messageData);
        await ChatConversation.updateOne({ _id: conversation._id }, { $set: { lastMessageAt: message.createdAt } });
      } else {
        message = { ...messageData, _id: `message-${Date.now()}` };
        global.ymentorMemoryStore.messages ||= [];
        global.ymentorMemoryStore.messages.push(message);
        conversation.lastMessageAt = message.createdAt;
      }
      return res.status(201).json(message);
    } catch (error) {
      console.error('Chat send error:', error);
      return res.status(400).json({ error: error.message || 'Unable to send message.' });
    }
  });

  async function findConversation(id) {
    if (mongoose.connection.readyState === 1 && mongoose.Types.ObjectId.isValid(id)) return ChatConversation.findById(id);
    return (global.ymentorMemoryStore?.conversations || []).find((item) => String(item._id) === id) || null;
  }

  async function findBooking(id) {
    if (mongoose.connection.readyState === 1 && mongoose.Types.ObjectId.isValid(id)) return Booking.findById(id);
    return (global.ymentorMemoryStore?.bookings || []).find((item) => String(item._id) === String(id)) || null;
  }

  function isParticipant(conversation, user) {
    const id = String(user._id || user.id);
    return String(conversation.mentorId) === id || String(conversation.menteeId) === id;
  }

  return router;
}

module.exports = createChatRouter;
