allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = "../build"

ext {
    compileSdkVersion = 37
    targetSdkVersion = 35
    minSdkVersion = 21
}

subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects { subproject ->
    def setCompileSdk = {
        if (subproject.hasProperty("android")) {
            subproject.android {
                compileSdk = 37
            }
        }
    }
    if (subproject.state.executed) {
        setCompileSdk()
    } else {
        subproject.afterEvaluate {
            setCompileSdk()
        }
    }
}

subprojects {
    project.evaluationDependsOn(":app")
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}
